### ISSUE TITLE
In os-selector.cfg, can I have a way to get a device-specific matching?

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#146]
Right now matching is based on either hw_model or default, e.g.

```
$ cat /opt/aeonztps/etc/profiles/default/cumulus/os-selector.cfg
default:
    exact_match: 3.1.1
    image: cumulus-linux-3.1.1-bcm-amd64.bin
MSN_2100:
    exact_match: 3.1.1
    image: cumulus-linux-3.1.1-mlx-amd64.bin
```

I would need a way to match a specific device, e.g. based on mgmt mac address or serial number. Ideally, any fact reported by the device could be a potential source for matching.

Thanks!
Ale

**Comment by jeremyschulman** [comment]
I would propose doing something like the following:

````yaml
---
mac=001122335566:
   exact_match: 3.1.1
    image: cumulus-linux-3.1.1-bcm-amd64.bin
````

would that be OK?

**Comment by bobbywatson3** [comment]
@acarpi I am working on this now. Here is the os-selector syntax I have in mind. Note that multiple criteria will be able to be used to match against a device.

```yaml
#
# 'default' means match hardware models not explicitly configured
#
default:
    regex_match: 3\.1\.[12]
    image: CumulusLinux-3.1.2-amd64.bin

device_group_a:
    # All keyword values here must match with the device for it to be accepted into this group.
    matches:
        hw_model:
            - Accton_AS6712
        mac_address:
            - 0123456789012
            - 0123456789013
            - 0123456789014

    # Perform code upgrade if version does not match this regex
    regex_match: 2\.5\.[67]

    # If a match is made, and regex does not match this OS is installed.
    image: CumulusLinux-2.5.7-amd64.bin-MAC

device_group_b:
    # All keyword values here must match with the device for it to be accepted into this group.
    matches:
        mac_address:
            - 0123456789012
        serial_number:
            - 1111111111

    # Perform code upgrade if version does not match this regex
    regex_match: 3\.1\.[12]

    # If a match is made, and regex does not match this OS is installed.
    image: CumulusLinux-3.1.2-amd64.bin-MAC
```
