### ISSUE TITLE
Provide a way to select different 'finally' script from OS selectors

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#187]
Hi,

it would be nice having the possibility to select different finally scripts from os-selector.cfg. Something along these lines

```
default:
  exact_match: 3.1.1
  image: cl-3.1.1-bcm-amd64.bin
device_group_mellanox:
  matches:
    serial_number:
    - AABBCCDD
  exact_match: 3.1.1
  image: cl-3.1.1-mlx-amd64.bin
  finally-script: 'finally-mellanox.sh'     <---- new
```
