### ISSUE TITLE
os_selector.cfg for EOS does not support mac_address

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aeon-ztps#223]
Was testing Aeon ZTPs today with a custom os_selector to do a targeted upgrade of a switch.

os_selector.cfg
```
    profile_switch-1:
      matches:
        mac_address:
            - 444CA80E4B8F
      exact_match: 4.18.4.1F
      image: EOS-4.18.4.1F.swi
      finally: finally.no.sdk
```

This profile never matched.

Looking at aeon_ztp/bin/eos_bootstrap.py, I see that mac_address is not posted.
```
    def post_device_facts(self):
        facts = self.dev.facts
        facts['ip_addr'] = self.dev.target
        facts = json.dumps(facts)
        dev_data = dict(
            ip_addr=self.dev.target,
            serial_number=self.dev.facts['serial_number'],
            hw_model=self.dev.facts['hw_model'],
            os_version=self.dev.facts['os_version'],
            os_name=self.os_name,
            facts=facts)
        dev_data['image_name'] = self.image_name
        dev_data['finally_script'] = self.finally_script

        requests.put(url='http://%s/api/devices/facts' % self.server, json=dev_data)
```

The documentation specifies the following are available as os_selectors:
```

The following facts are supported to be used as a match criteria:
os_name
vendor
hw_part_number
hostname
fqdn
virtual (bool)
service_tag
os_version
hw_version
mac_address
serial_number
hw_model
ip_addr
```

The documentation also shows examples of device facts used with mac addresses:

```
Accton_Switches:

    # All keyword values here must match with the
    # device for it to be accepted into this group.
    matches:
        hw_model:
            - Accton_AS6712
        mac_address:
            - 0123456789012
            - 0123456789013
            - 0123456789014
```

Viewing the device facts gathered from the EOS device:

```
{
  "count": 1, 
  "items": [
    {
      "created_at": "2017-10-25T19:27:01.933277", 
      "facts": "{\"os_name\": \"eos\", \"vendor\": \"arista\", \"hw_part_number\": null, \"mac_address\": \"44:4c:a8:0e:4b:8f\", \"serial_number\": \"JPE15260065\", \"chassis_id\": null, \"fqdn\": \"localhost.dc1.apstra.com\", \"os_version\": \"4.16.6M\", \"virtual\": false, \"hw_model\": \"DCS-7050QX-32-F\", \"hw_version\": \"02.11\", \"ip_addr\": \"172.20.197.6\", \"hw_part_version\": null, \"hostname\": \"localhost\"}", 
      "finally_script": null, 
      "hw_model": "DCS-7050QX-32-F", 
      "image_name": null, 
      "ip_addr": "172.20.197.6", 
      "message": "device bootstrap completed", 
      "os_name": "eos", 
      "os_version": "4.16.6M", 
      "serial_number": "JPE15260065", 
      "state": "DONE", 
      "updated_at": "2017-10-25T19:33:10.448822"
    }
  ]
}

```

It seems that 'facts' is serialized as a string?
